apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: secrets
  name: secrets
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: secrets
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: secrets
    spec:
      containers:
        - image: mirriad/secret-resolver:0.3.0
          name: secrets
          resources: {}
          volumeMounts:
            - mountPath: /etc/vault
              name: secrets-claim0
            - mountPath: /vault
              name: composeorganisationstack-token
      restartPolicy: Always
      volumes:
        - name: secrets-claim0
          persistentVolumeClaim:
            claimName: secrets-claim0
        - name: composeorganisationstack-token
          persistentVolumeClaim:
            claimName: composeorganisationstack-token
status: {}
