apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: user-admin
  name: user-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: user-admin
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: user-admin
    spec:
      containers:
        - image: rancher/dns-service
          name: user-admin
          resources: {}
      restartPolicy: Always
status: {}
